-- Phase 7 - Prepare RANGE partitioning for the largest time-based warehouse facts.
--
-- Requirement mapping:
-- payments_table    -> warehouse.fact_payments_partitioned (detected date column)
-- sensor_data_table -> warehouse.fact_telemetry_partitioned (detected timestamp column)
--
-- The current pipeline still writes into staging tables. This script prepares
-- partitioned warehouse tables and a migration path without inventing a new schema.

DROP FUNCTION IF EXISTS pg_temp.build_partition_parent_ddl(TEXT, TEXT, TEXT, TEXT[]);
DROP FUNCTION IF EXISTS pg_temp.run_if_columns_exist(TEXT, TEXT, TEXT[], TEXT);
DROP FUNCTION IF EXISTS pg_temp.first_existing_column(TEXT, TEXT, TEXT[]);
DROP FUNCTION IF EXISTS pg_temp.table_exists(TEXT, TEXT);
DROP FUNCTION IF EXISTS pg_temp.column_exists(TEXT, TEXT, TEXT);

CREATE OR REPLACE FUNCTION pg_temp.column_exists(
    schema_name TEXT,
    relation_name TEXT,
    column_name TEXT
) RETURNS BOOLEAN
LANGUAGE sql
AS $$
    SELECT EXISTS (
        SELECT 1
        FROM pg_attribute a
        JOIN pg_class c
            ON c.oid = a.attrelid
        JOIN pg_namespace n
            ON n.oid = c.relnamespace
        WHERE n.nspname = schema_name
          AND c.relname = relation_name
          AND a.attname = column_name
          AND a.attnum > 0
          AND NOT a.attisdropped
    );
$$;

CREATE OR REPLACE FUNCTION pg_temp.table_exists(
    schema_name TEXT,
    relation_name TEXT
) RETURNS BOOLEAN
LANGUAGE sql
AS $$
    SELECT EXISTS (
        SELECT 1
        FROM information_schema.tables t
        WHERE t.table_schema = schema_name
          AND t.table_name = relation_name
    );
$$;

CREATE OR REPLACE FUNCTION pg_temp.first_existing_column(
    schema_name TEXT,
    relation_name TEXT,
    candidate_columns TEXT[]
) RETURNS TEXT
LANGUAGE plpgsql
AS $$
DECLARE
    candidate_column TEXT;
BEGIN
    FOREACH candidate_column IN ARRAY candidate_columns LOOP
        IF EXISTS (
            SELECT 1
            FROM pg_attribute a
            JOIN pg_class c
                ON c.oid = a.attrelid
            JOIN pg_namespace n
                ON n.oid = c.relnamespace
            WHERE n.nspname = schema_name
              AND c.relname = relation_name
              AND a.attname = candidate_column
              AND a.attnum > 0
              AND NOT a.attisdropped
        ) THEN
            RETURN candidate_column;
        END IF;
    END LOOP;

    RETURN NULL;
END;
$$;

CREATE OR REPLACE FUNCTION pg_temp.run_if_columns_exist(
    schema_name TEXT,
    relation_name TEXT,
    required_columns TEXT[],
    ddl TEXT
) RETURNS VOID
LANGUAGE plpgsql
AS $$
DECLARE
    missing_columns TEXT[];
BEGIN
    IF NOT pg_temp.table_exists(schema_name, relation_name) THEN
        RAISE NOTICE 'Skipping %.% because the table does not exist', schema_name, relation_name;
        RETURN;
    END IF;

    SELECT array_agg(required_column)
    INTO missing_columns
    FROM unnest(required_columns) AS required_column
    WHERE NOT pg_temp.column_exists(schema_name, relation_name, required_column);

    IF missing_columns IS NOT NULL THEN
        RAISE NOTICE 'Skipping %.% because required columns are missing: %', schema_name, relation_name, missing_columns;
        RETURN;
    END IF;

    EXECUTE ddl;
END;
$$;

CREATE OR REPLACE FUNCTION pg_temp.build_partition_parent_ddl(
    schema_name TEXT,
    source_table TEXT,
    target_table TEXT,
    candidate_columns TEXT[]
) RETURNS TEXT
LANGUAGE plpgsql
AS $$
DECLARE
    column_definitions TEXT;
    resolved_partition_column TEXT;
BEGIN
    WITH live_columns AS (
        SELECT
            a.attnum AS ordinal_position,
            a.attname AS column_name,
            format(
                '%I %s%s%s%s',
                a.attname,
                pg_catalog.format_type(a.atttypid, a.atttypmod),
                CASE
                    WHEN a.attidentity = 'a' THEN ' GENERATED ALWAYS AS IDENTITY'
                    WHEN a.attidentity = 'd' THEN ' GENERATED BY DEFAULT AS IDENTITY'
                    ELSE ''
                END,
                CASE
                    WHEN a.attidentity = '' AND ad.adbin IS NOT NULL THEN format(' DEFAULT %s', pg_get_expr(ad.adbin, ad.adrelid))
                    ELSE ''
                END,
                CASE
                    WHEN a.attnotnull THEN ' NOT NULL'
                    ELSE ''
                END
            ) AS column_definition
        FROM pg_attribute a
        JOIN pg_class c
            ON c.oid = a.attrelid
        JOIN pg_namespace n
            ON n.oid = c.relnamespace
        LEFT JOIN pg_attrdef ad
            ON ad.adrelid = a.attrelid
           AND ad.adnum = a.attnum
        WHERE n.nspname = schema_name
          AND c.relname = source_table
          AND a.attnum > 0
          AND NOT a.attisdropped
    )
    SELECT
        string_agg(column_definition, E',\n    ' ORDER BY ordinal_position),
        (
            SELECT lc.column_name
            FROM unnest(candidate_columns) WITH ORDINALITY AS candidate(column_name, ord)
            JOIN live_columns lc
                ON lc.column_name = candidate.column_name
            ORDER BY candidate.ord
            LIMIT 1
        )
    INTO column_definitions, resolved_partition_column
    FROM live_columns;

    IF column_definitions IS NULL THEN
        RETURN NULL;
    END IF;

    IF resolved_partition_column IS NULL THEN
        RETURN NULL;
    END IF;

    RETURN format(
        E'CREATE TABLE IF NOT EXISTS %I.%I (\n    %s\n) PARTITION BY RANGE (%I)',
        schema_name,
        target_table,
        column_definitions,
        resolved_partition_column
    );
END;
$$;

DO $$
DECLARE
    payments_partition_column TEXT;
    telemetry_partition_column TEXT;
    payments_partition_ddl TEXT;
    telemetry_partition_ddl TEXT;
BEGIN
    payments_partition_column := pg_temp.first_existing_column(
        'warehouse',
        'fact_payments',
        ARRAY['payment_date', 'transaction_date', 'created_at']
    );

    telemetry_partition_column := pg_temp.first_existing_column(
        'warehouse',
        'fact_telemetry',
        ARRAY['telemetry_timestamp', 'timestamp', 'created_at']
    );

    RAISE NOTICE 'fact_payments partition column: %', payments_partition_column;
    RAISE NOTICE 'fact_telemetry partition column: %', telemetry_partition_column;

    IF pg_temp.table_exists('warehouse', 'fact_payments')
       AND payments_partition_column IS NOT NULL THEN
        payments_partition_ddl := pg_temp.build_partition_parent_ddl(
            'warehouse',
            'fact_payments',
            'fact_payments_partitioned',
            ARRAY['payment_date', 'transaction_date', 'created_at']
        );

        IF payments_partition_ddl IS NOT NULL THEN
            EXECUTE payments_partition_ddl;
        ELSE
            RAISE NOTICE 'Skipping warehouse.fact_payments_partitioned because column metadata could not be derived';
        END IF;
    ELSE
        RAISE NOTICE 'Skipping warehouse.fact_payments_partitioned because warehouse.fact_payments or a usable partition column is missing';
    END IF;

    IF pg_temp.table_exists('warehouse', 'fact_telemetry')
       AND telemetry_partition_column IS NOT NULL THEN
        telemetry_partition_ddl := pg_temp.build_partition_parent_ddl(
            'warehouse',
            'fact_telemetry',
            'fact_telemetry_partitioned',
            ARRAY['telemetry_timestamp', 'timestamp', 'created_at']
        );

        IF telemetry_partition_ddl IS NOT NULL THEN
            EXECUTE telemetry_partition_ddl;
        ELSE
            RAISE NOTICE 'Skipping warehouse.fact_telemetry_partitioned because column metadata could not be derived';
        END IF;
    ELSE
        RAISE NOTICE 'Skipping warehouse.fact_telemetry_partitioned because warehouse.fact_telemetry or a usable partition column is missing';
    END IF;
END;
$$;

DO $$
DECLARE
    payments_partition_column TEXT;
    telemetry_partition_column TEXT;
BEGIN
    payments_partition_column := pg_temp.first_existing_column(
        'warehouse',
        'fact_payments_partitioned',
        ARRAY['payment_date', 'transaction_date', 'created_at']
    );

    telemetry_partition_column := pg_temp.first_existing_column(
        'warehouse',
        'fact_telemetry_partitioned',
        ARRAY['telemetry_timestamp', 'timestamp', 'created_at']
    );

    RAISE NOTICE 'fact_payments_partitioned detected partition column: %', payments_partition_column;
    RAISE NOTICE 'fact_telemetry_partitioned detected partition column: %', telemetry_partition_column;

    IF payments_partition_column IS NOT NULL THEN
        EXECUTE format(
            'CREATE INDEX IF NOT EXISTS idx_fact_payments_partitioned_partition_date ON warehouse.fact_payments_partitioned (%I)',
            payments_partition_column
        );
    END IF;

    IF pg_temp.column_exists('warehouse', 'fact_payments_partitioned', 'sales_key') THEN
        EXECUTE 'CREATE INDEX IF NOT EXISTS idx_fact_payments_partitioned_sales_key ON warehouse.fact_payments_partitioned (sales_key)';
    END IF;

    IF telemetry_partition_column IS NOT NULL THEN
        EXECUTE format(
            'CREATE INDEX IF NOT EXISTS idx_fact_telemetry_partitioned_partition_ts ON warehouse.fact_telemetry_partitioned (%I)',
            telemetry_partition_column
        );
    END IF;

    IF telemetry_partition_column IS NOT NULL
       AND pg_temp.column_exists('warehouse', 'fact_telemetry_partitioned', 'vehicle_key') THEN
        EXECUTE format(
            'CREATE INDEX IF NOT EXISTS idx_fact_telemetry_partitioned_vehicle_timestamp ON warehouse.fact_telemetry_partitioned (vehicle_key, %I)',
            telemetry_partition_column
        );
    END IF;
END;
$$;

DO $$
DECLARE
    month_start DATE := date_trunc('month', CURRENT_DATE)::date - INTERVAL '2 months';
    month_end DATE;
    part_name TEXT;
    payments_partition_column TEXT;
    telemetry_partition_column TEXT;
BEGIN
    payments_partition_column := pg_temp.first_existing_column(
        'warehouse',
        'fact_payments_partitioned',
        ARRAY['payment_date', 'transaction_date', 'created_at']
    );

    telemetry_partition_column := pg_temp.first_existing_column(
        'warehouse',
        'fact_telemetry_partitioned',
        ARRAY['telemetry_timestamp', 'timestamp', 'created_at']
    );

    RAISE NOTICE 'monthly partition creation uses payments column: %', payments_partition_column;
    RAISE NOTICE 'monthly partition creation uses telemetry column: %', telemetry_partition_column;

    IF NOT pg_temp.table_exists('warehouse', 'fact_payments_partitioned')
       AND NOT pg_temp.table_exists('warehouse', 'fact_telemetry_partitioned') THEN
        RAISE NOTICE 'Skipping partition creation because no partitioned base tables were created';
        RETURN;
    END IF;

    FOR i IN 1..15 LOOP
        month_end := (month_start + INTERVAL '1 month')::date;

        IF pg_temp.table_exists('warehouse', 'fact_payments_partitioned')
           AND payments_partition_column IS NOT NULL THEN
            part_name := format('fact_payments_%s', to_char(month_start, 'YYYY_MM'));
            EXECUTE format(
                'CREATE TABLE IF NOT EXISTS warehouse.%I PARTITION OF warehouse.fact_payments_partitioned FOR VALUES FROM (%L) TO (%L)',
                part_name,
                month_start,
                month_end
            );
        END IF;

        IF pg_temp.table_exists('warehouse', 'fact_telemetry_partitioned')
           AND telemetry_partition_column IS NOT NULL THEN
            part_name := format('fact_telemetry_%s', to_char(month_start, 'YYYY_MM'));
            EXECUTE format(
                'CREATE TABLE IF NOT EXISTS warehouse.%I PARTITION OF warehouse.fact_telemetry_partitioned FOR VALUES FROM (%L) TO (%L)',
                part_name,
                month_start,
                month_end
            );
        END IF;

        month_start := month_end;
    END LOOP;
END $$;

DO $$
DECLARE
    source_columns TEXT;
    payments_partition_column TEXT;
    telemetry_partition_column TEXT;
BEGIN
    payments_partition_column := pg_temp.first_existing_column(
        'warehouse',
        'fact_payments',
        ARRAY['payment_date', 'transaction_date', 'created_at']
    );

    telemetry_partition_column := pg_temp.first_existing_column(
        'warehouse',
        'fact_telemetry',
        ARRAY['telemetry_timestamp', 'timestamp', 'created_at']
    );

    RAISE NOTICE 'data copy uses payments column: %', payments_partition_column;
    RAISE NOTICE 'data copy uses telemetry column: %', telemetry_partition_column;

    IF pg_temp.table_exists('warehouse', 'fact_payments_partitioned') THEN
        EXECUTE 'CREATE TABLE IF NOT EXISTS warehouse.fact_payments_default PARTITION OF warehouse.fact_payments_partitioned DEFAULT';

        SELECT string_agg(quote_ident(column_name), ', ' ORDER BY ordinal_position)
        INTO source_columns
        FROM information_schema.columns
        WHERE table_schema = 'warehouse'
          AND table_name = 'fact_payments';

        IF source_columns IS NOT NULL AND payments_partition_column IS NOT NULL THEN
            IF pg_temp.column_exists('warehouse', 'fact_payments', 'payment_id')
               AND pg_temp.column_exists('warehouse', 'fact_payments_partitioned', 'payment_id') THEN
                EXECUTE format(
                    'INSERT INTO warehouse.fact_payments_partitioned (%1$s) SELECT %1$s FROM warehouse.fact_payments src WHERE src.%2$I IS NOT NULL AND NOT EXISTS (SELECT 1 FROM warehouse.fact_payments_partitioned tgt WHERE tgt.payment_id = src.payment_id)',
                    source_columns,
                    payments_partition_column
                );
            ELSE
                EXECUTE format(
                    'INSERT INTO warehouse.fact_payments_partitioned (%1$s) SELECT %1$s FROM warehouse.fact_payments src WHERE src.%2$I IS NOT NULL',
                    source_columns,
                    payments_partition_column
                );
            END IF;
        END IF;
    END IF;

    IF pg_temp.table_exists('warehouse', 'fact_telemetry_partitioned') THEN
        EXECUTE 'CREATE TABLE IF NOT EXISTS warehouse.fact_telemetry_default PARTITION OF warehouse.fact_telemetry_partitioned DEFAULT';

        SELECT string_agg(quote_ident(column_name), ', ' ORDER BY ordinal_position)
        INTO source_columns
        FROM information_schema.columns
        WHERE table_schema = 'warehouse'
          AND table_name = 'fact_telemetry';

        IF source_columns IS NOT NULL AND telemetry_partition_column IS NOT NULL THEN
            IF pg_temp.column_exists('warehouse', 'fact_telemetry', 'telemetry_id')
               AND pg_temp.column_exists('warehouse', 'fact_telemetry_partitioned', 'telemetry_id') THEN
                EXECUTE format(
                    'INSERT INTO warehouse.fact_telemetry_partitioned (%1$s) SELECT %1$s FROM warehouse.fact_telemetry src WHERE src.%2$I IS NOT NULL AND NOT EXISTS (SELECT 1 FROM warehouse.fact_telemetry_partitioned tgt WHERE tgt.telemetry_id = src.telemetry_id)',
                    source_columns,
                    telemetry_partition_column
                );
            ELSE
                EXECUTE format(
                    'INSERT INTO warehouse.fact_telemetry_partitioned (%1$s) SELECT %1$s FROM warehouse.fact_telemetry src WHERE src.%2$I IS NOT NULL',
                    source_columns,
                    telemetry_partition_column
                );
            END IF;
        END IF;
    END IF;
END $$;
